var logicUtils = require("./compile.js");
var println = logicUtils.println;
var axioms = [];
var map = {};
map.A = 'CONTAINS';
map.B = 'CONTAINS';
map.C = 'CONTAINS';
map.D = 'IN';
map.E = 'IN';
map.F = 'INTERSECTS';
map.G = 'EITHER';
axioms.push('(A) C (B)\nA C\tC B\tA B');
axioms.push('(D) C (E) \nD E\tC E\tD C');
axioms.push('(F) D (E (G))\nD E\tE G\tF D\tF G\tF G');
var pack = logicUtils.compileAxioms(axioms,map);
var lns = pack[1];
var graph = pack[0];
console.log(graph[0]);
lns.forEach(function (ln) { console.log(println(ln)); });
